version: "3.8"

services:

  evil-client-server:
    image: csrf-client-server
    volumes:
      # mount the app code into running container to allow live editing
      - type: bind
        source: ./evil-client-server/client-server
        target: /var/www/server/client-server
    build:
      context: evil-client-server
      dockerfile: Dockerfile
    ports:
      - 5001:5000

  resource-server:
    image: csrf-resource-server
    volumes:
      # mount the app code into running container to allow live editing
      - type: bind
        source: ./resource-server/resource-server
        target: /var/www/server/resource-server
    build:
      context: resource-server
      dockerfile: Dockerfile
    ports:
      - 5002:5000

